<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Estado de cuenta</title>
<style>body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#172b4d}h1{font-size:20px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{text-align:left;padding:8px 5px;border-bottom:1px solid #dde3ed}th{background:#edf3f9}tfoot{font-weight:bold}footer{margin-top:24px;color:#627186}</style></head><body>
@php use App\Services\HospitalInvoiceLedger as Ledger; @endphp
<h1>Estado de cuenta</h1><p>Hospital: {{ $hospital?->name }} · MXN</p><p>Emisión: {{ $from ?: 'Sin límite' }} al {{ $to ?: 'Sin límite' }} · Corte: {{ today()->format('d/m/Y') }}</p>
<table><thead><tr><th>Factura</th><th>Emisión</th><th>Vencimiento</th><th>Importe</th><th>Pagos aplicados</th><th>Saldo</th><th>Estado de pago</th></tr></thead><tbody>
@forelse ($rows as $invoice)<tr><td>{{ $invoice['folio'] }}</td><td>{{ $invoice['date']?->format('d/m/Y') ?? 'Sin registrar' }}</td><td>{{ $invoice['due']?->format('d/m/Y') ?? '—' }}</td><td>{{ Ledger::money($invoice['total']) }}</td><td>{{ Ledger::money($invoice['paid']) }}</td><td>{{ Ledger::money($invoice['balance']) }}</td><td>{{ ['pending'=>'Pendiente','partial'=>'Pago parcial','paid'=>'Pagada','unknown'=>'Sin importe'][$invoice['state']] }}{{ $invoice['overdue'] ? ' · '.$invoice['days_overdue'].' días vencida' : '' }}</td></tr>@empty<tr><td colspan="7">Sin facturas para estos filtros.</td></tr>@endforelse
</tbody><tfoot><tr><td colspan="3">Total de las facturas seleccionadas</td><td>{{ Ledger::money($rows->sum('total')) }}</td><td>{{ Ledger::money($rows->sum('paid')) }}</td><td>{{ Ledger::money($rows->sum('balance')) }}</td><td></td></tr></tfoot></table>
@if ($rows->whereNull('total')->count())<p>Los importes sin registrar no están incluidos en los totales.</p>@endif
<footer>Los pagos reportados no se descuentan hasta su validación por Prodifem. Este estado de cuenta no sustituye al comprobante fiscal.</footer></body></html>
