<x-admin-layout>
    <div class="mb-5"><h1 class="text-2xl font-bold">{{ $mode === 'create' ? 'Agregar consumible' : 'Editar consumible' }}</h1><p class="text-sm text-gray-500">Registra el insumo genérico y sus presentaciones; los lotes se administran desde almacenes.</p></div>
    <form method="POST" action="{{ $mode === 'create' ? route('admin.consumables.catalog.store') : route('admin.consumables.catalog.update', $item) }}" class="rounded border border-gray-200 bg-white p-6 shadow-sm">
        @csrf @if($mode === 'edit') @method('PUT') @endif
        <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-1 block text-sm font-medium">Denominación genérica</label><input name="name" value="{{ old('name', $item->name) }}" required class="w-full rounded border-gray-300">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-medium">Unidad</label><input name="unit" value="{{ old('unit', $item->unit ?: 'pieza') }}" required class="w-full rounded border-gray-300"></div></div>
        <div class="mt-6 border-t pt-5" x-data="{ count: {{ max(1, $item->catalogPresentations->count()) }} }"><div class="mb-3 flex items-center justify-between"><h2 class="text-lg font-bold">Presentaciones</h2><button type="button" @click="count++" class="rounded bg-blue-900 px-3 py-2 text-xs font-bold text-white">Agregar presentación</button></div>
            @php($existing = $item->catalogPresentations->values())
            <template x-for="index in count" :key="index"><div class="mb-4 rounded border border-gray-200 p-4"><input type="hidden" :name="`presentations[${index - 1}][id]`" :value="index <= {{ $existing->count() }} ? {{ json_encode($existing->pluck('id')->values()) }}[index - 1] : ''"><div class="grid gap-4 md:grid-cols-3"><div><label class="mb-1 block text-sm font-medium">Presentación</label><input :name="`presentations[${index - 1}][presentation]`" :value="index <= {{ $existing->count() }} ? {{ json_encode($existing->pluck('presentation')->values()) }}[index - 1] : ''" required class="w-full rounded border-gray-300"></div><div><label class="mb-1 block text-sm font-medium">Nombre comercial</label><input :name="`presentations[${index - 1}][commercial_name]`" :value="index <= {{ $existing->count() }} ? {{ json_encode($existing->pluck('commercial_name')->values()) }}[index - 1] : ''" class="w-full rounded border-gray-300"></div><div><label class="mb-1 block text-sm font-medium">Fabricante</label><input :name="`presentations[${index - 1}][manufacturer]`" :value="index <= {{ $existing->count() }} ? {{ json_encode($existing->pluck('manufacturer')->values()) }}[index - 1] : ''" class="w-full rounded border-gray-300"></div></div></div></template>
        </div><div class="mt-6 flex justify-end gap-2"><a href="{{ route('admin.catalogo-listas.catalog', 'consumibles') }}" class="rounded bg-gray-100 px-4 py-2 text-sm font-semibold text-gray-700">Cancelar</a><button class="rounded bg-green-600 px-4 py-2 text-sm font-semibold text-white">{{ $mode === 'create' ? 'Guardar consumible' : 'Actualizar consumible' }}</button></div>
    </form>
</x-admin-layout>
